[tool.bumpversion]
current_version = "0.3.5"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = '{current_version}'
replace = '{new_version}'
tag = true
sign_tags = false
commit = true
message = "Bump version: {current_version} → {new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag_name = "v{new_version}"
allow_dirty = false
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "src/repeatradar/__init__.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""
